export enum CategoryEnum {
  Rent = 1,
  Garage = 2,
  Utilities = 3,
  RentersInsurance = 4,
  Cat = 5,
  Internet = 6,
  CarInsurance = 7,
  TV = 8,
  Transportation = 9,
  Groceries = 10,
  Healthcare = 11,
  DentalVision = 12,
  RothIRA = 13,
  FourZeroOneK = 14,
  HSA = 15,
  CarPayment = 16,
  StudentLoans = 17,
  AnnualFees = 18,
  HouseSavings = 19,
  VacationSavings = 20,
  Golf = 21,
  EatingOut = 22,
  Play = 23
}